[0.087s] Invoking command in '/home/pritam/ros2_WS/build/custom_interfaces': CMAKE_PREFIX_PATH=/opt/ros/humble /usr/bin/cmake /home/pritam/ros2_WS/src/custom_interfaces -DCMAKE_INSTALL_PREFIX=/home/pritam/ros2_WS/install/custom_interfaces
[0.526s] -- Found ament_cmake: 1.3.12 (/opt/ros/humble/share/ament_cmake/cmake)
[0.526s] -- Found rosidl_default_generators: 1.2.0 (/opt/ros/humble/share/rosidl_default_generators/cmake)
[0.531s] -- Using all available rosidl_typesupport_c: rosidl_typesupport_fastrtps_c;rosidl_typesupport_introspection_c
[0.532s] -- Found rosidl_adapter: 3.1.7 (/opt/ros/humble/share/rosidl_adapter/cmake)
[0.844s] -- Using all available rosidl_typesupport_cpp: rosidl_typesupport_fastrtps_cpp;rosidl_typesupport_introspection_cpp
[1.180s] [31mCMake Error at /opt/ros/humble/share/rosidl_adapter/cmake/rosidl_adapt_interfaces.cmake:59 (message):
[1.180s]   execute_process(/usr/bin/python3 -m rosidl_adapter --package-name
[1.181s]   custom_interfaces --arguments-file
[1.181s]   /home/pritam/ros2_WS/build/custom_interfaces/rosidl_adapter__arguments__custom_interfaces.json
[1.181s]   --output-dir
[1.181s]   /home/pritam/ros2_WS/build/custom_interfaces/rosidl_adapter/custom_interfaces
[1.181s]   --output-file
[1.181s]   /home/pritam/ros2_WS/build/custom_interfaces/rosidl_adapter/custom_interfaces.idls)
[1.181s]   returned error code 1:
[1.181s] 
[1.182s]   Traceback (most recent call last):
[1.182s] 
[1.182s]     File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[1.182s]       return _run_code(code, main_globals, None,
[1.182s]     File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
[1.182s]       exec(code, run_globals)
[1.182s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__main__.py", line 19, in <module>
[1.182s]       sys.exit(main())
[1.182s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/main.py", line 53, in main
[1.182s]       abs_idl_file = convert_to_idl(
[1.182s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__init__.py", line 24, in convert_to_idl
[1.182s]       return convert_srv_to_idl(
[1.182s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/srv/__init__.py", line 28, in convert_srv_to_idl
[1.182s]       srv = parse_service_string(package_name, input_file.stem, content)
[1.182s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 859, in parse_service_string
[1.182s]       request_message = parse_message_string(
[1.183s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 544, in parse_message_string
[1.183s]       msg = MessageSpecification(pkg_name, msg_name, fields, constants)
[1.183s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 388, in __init__
[1.183s]       self.base_type = BaseType(
[1.183s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 205, in __init__
[1.183s]       raise InvalidResourceName(
[1.183s] 
[1.183s]   rosidl_adapter.parser.InvalidResourceName: 'add_two_ints_Request' is an
[1.183s]   invalid message name.  It should have the pattern '^[A-Z][A-Za-z0-9]*$'
[1.183s] 
[1.183s] Call Stack (most recent call first):
[1.183s]   /opt/ros/humble/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:130 (rosidl_adapt_interfaces)
[1.183s]   CMakeLists.txt:18 (rosidl_generate_interfaces)
[1.183s] 
[1.183s] [0m
[1.183s] -- Configuring incomplete, errors occurred!
[1.183s] See also "/home/pritam/ros2_WS/build/custom_interfaces/CMakeFiles/CMakeOutput.log".
[1.190s] Invoked command in '/home/pritam/ros2_WS/build/custom_interfaces' returned '1': CMAKE_PREFIX_PATH=/opt/ros/humble /usr/bin/cmake /home/pritam/ros2_WS/src/custom_interfaces -DCMAKE_INSTALL_PREFIX=/home/pritam/ros2_WS/install/custom_interfaces
